### ISSUE TITLE
Feeds seem to no longer crawl

### ISSUE THREAD

**Issue by MaxTechnics** [Qrivi/Feednite#11]
Not sure if it has to do with the site redesign or something else. It runs into 'internal server error'

Edit: Checking logs i'm getting this:
```
TypeError: Cannot read properties of undefined (reading 'replace')
    at writeCdata (/Users/maxim/Documents/GitHub/Feednite/node_modules/xml-js/lib/js2xml.js:111:142)
    at writeElementsCompact (/Users/maxim/Documents/GitHub/Feednite/node_modules/xml-js/lib/js2xml.js:292:116)
    at writeElementCompact (/Users/maxim/Documents/GitHub/Feednite/node_modules/xml-js/lib/js2xml.js:272:12)
    at writeElementsCompact (/Users/maxim/Documents/GitHub/Feednite/node_modules/xml-js/lib/js2xml.js:295:73)
    at writeElementCompact (/Users/maxim/Documents/GitHub/Feednite/node_modules/xml-js/lib/js2xml.js:272:12)
    at writeElementsCompact (/Users/maxim/Documents/GitHub/Feednite/node_modules/xml-js/lib/js2xml.js:295:73)
    at writeElementCompact (/Users/maxim/Documents/GitHub/Feednite/node_modules/xml-js/lib/js2xml.js:272:12)
    at writeElementsCompact (/Users/maxim/Documents/GitHub/Feednite/node_modules/xml-js/lib/js2xml.js:295:73)
    at writeElementCompact (/Users/maxim/Documents/GitHub/Feednite/node_modules/xml-js/lib/js2xml.js:272:12)
    at writeElementsCompact (/Users/maxim/Documents/GitHub/Feednite/node_modules/xml-js/lib/js2xml.js:295:73)
```

Fortnite's api still returns data, it must be something happening during parsing. I have too little knowledge about rss to dig deeper right now

**Comment by MaxTechnics** [comment]
Seems to have fixed itself
